
name: MSBuild
on: [push]
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        vs-version: '[16.11,16.12)'
        vs-prerelease: false
        msbuild-architecture: x64

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
      run: |
        where msbuild
      #shell: bash
      #run: |
        msbuild -version
        choco install -y --no-progress 7zip
        busybox
        busybox date '+%Y.%m.%d.%H.%M.%S'
        busybox uname -a
        echo "PATH=C:\Program Files\Git\bin;C:\Windows\System32;C:\Windows;C:\ProgramData\Chocolatey\bin" >> "%GITHUB_ENV%"
        echo "%GITHUB_ENV%"

        cat <<<EOF > build.sh
        rm -rf build*
        mkdir -p build_dynamic_mt build_static_mt build_dynamic_md build_static_md
        cd src
        call msvcbuild.bat
        cp -rf lua51.lib luajit.lib luajit.exe lua51.dll include include ../build_dynamic_mt
        call msvcbuild.bat static
        cp -rf lua51.lib luajit.lib luajit.exe lua51.dll include include ../build_static_mt
        sed -i "s;/MT;/MD;g" msvcbuild.bat
        call msvcbuild.bat
        cp -rf lua51.lib luajit.lib luajit.exe lua51.dll include include ../build_dynamic_md
        call msvcbuild.bat static
        cp -rf lua51.lib luajit.lib luajit.exe lua51.dll include include ../build_static_md
        cd ..
        EOF
        busybox -x build.sh

        7z a build_dynamic_mt.7z build_dynamic_mt/*
        7z a build_static_mt.7z  build_static_mt/*
        7z a build_dynamic_md.7z build_dynamic_md/*
        7z a build_static_md.7z  build_static_md/*
