
name: MSBuild
on: [push]
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
jobs:
  build:
    runs-on: windows-2019
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        vs-version: '[16.11,16.12)'
        vs-prerelease: false
        msbuild-architecture: x64

    - name: Add msbuild to PATH
      uses: microsoft/setup-msbuild@v1.0.2
    - shell: cmd
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvarsx86_amd64.bat"
        msbuild -version
        choco install -y --no-progress busybox 7zip
        busybox
        busybox which msbuild
        busybox date '+%Y.%m.%d.%H.%M.%S'
        busybox uname -a
        echo "PATH=C:\Program Files\Git\bin;C:\Windows\System32;C:\Windows;C:\ProgramData\Chocolatey\bin" >> "$GITHUB_ENV"
        echo "$GITHUB_ENV"

        busybox echo "-------------------------------------"
        busybox sed -i "s/; /\r/g" build.sh
        busybox echo "-------------------------------------"
        busybox echo bash -x build.sh
        busybox bash -x build.sh static  mt
        busybox bash -x build.sh dynamic mt
        busybox bash -x build.sh static  md
        busybox bash -x build.sh dynamic md
        busybox echo "-------------------------------------"

    - name: Create release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

  upload-assets:
    needs: build
    runs-on: windows-2019
    strategy:
      matrix:
        asset: ['build_dynamic_mt.7z', 'build_static_mt.7z', 'build_dynamic_md.7z', 'build_static_md.7z']
    steps:
      - name: Upload Release Asset ${{ matrix.asset }}
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          #upload_url: ${{ needs.build.outputs.upload_url }} # この行は前のジョブの出力を正しく参照していることを確認してください。
          asset_path: ${{ matrix.asset }}
          asset_name: ${{ matrix.asset }}
          asset_content_type: application/x-7z-compressed
