name: MSBuild
on: [push]
run-name: Deploy to ${{ inputs.deploy_target }} by @${{ github.actor }}
jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # Version of Visual Studio to search; defaults to latest if not specified
          vs-version: '[16.11,16.12)' # optional
          # Enable searching for pre-release versions of Visual Studio/MSBuild
          vs-prerelease: false # optional
          # The preferred processor architecture of MSBuild. Can be either "x86", "x64", or "arm64". "x64" is only available from Visual Studio version 17.0 and later.
          msbuild-architecture: x64
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
        run: |
          msbuild -version
          choco install -y --no-progress busybox 7zip
          busybox
          busybox date '+%Y.%m.%d.%H.%M.%S'
          busybox uname -a
          busybox pwd
